apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec: # specs do deployment
  replicas: 3
  selector: # selector utilizado para criar o service
    matchLabels:
      app: nginx
  template: # referente ao POD
    metadata:
      labels:
        app: nginx
    spec: # spec do POD
      containers:
      - name: nginx
        image: nginx:1.19.3-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: nginx-conf
          subPath: index.html

      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-index-html
